name: de_jobs
version: "1.0.0"
config-version: 2
profile: de_jobs

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  de_jobs:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  de_jobs:
    +schema: seeds
    skills:
      +column_types:
        skill_key: text
        display_name: text
        category: text
        pattern: text
